// countryList.js
export const countries = [
    { value: "AF", menu: "Afghanistan" },
    { value: "AL", menu: "Albania" },
    { value: "DZ", menu: "Algeria" },
    { value: "AD", menu: "Andorra" },
    { value: "AO", menu: "Angola" },
    { value: "AG", menu: "Antigua and Barbuda" },
    { value: "AR", menu: "Argentina" },
    { value: "AM", menu: "Armenia" },
    { value: "AU", menu: "Australia" },
    { value: "AT", menu: "Austria" },
    { value: "AZ", menu: "Azerbaijan" },
    { value: "BS", menu: "Bahamas" },
    { value: "BH", menu: "Bahrain" },
    { value: "BD", menu: "Bangladesh" },
    { value: "BB", menu: "Barbados" },
    { value: "BY", menu: "Belarus" },
    { value: "BE", menu: "Belgium" },
    { value: "BZ", menu: "Belize" },
    { value: "BJ", menu: "Benin" },
    { value: "BT", menu: "Bhutan" },
    { value: "BO", menu: "Bolivia" },
    { value: "BA", menu: "Bosnia and Herzegovina" },
    { value: "BW", menu: "Botswana" },
    { value: "BR", menu: "Brazil" },
    { value: "BN", menu: "Brunei" },
    { value: "BG", menu: "Bulgaria" },
    { value: "BF", menu: "Burkina Faso" },
    { value: "BI", menu: "Burundi" },
    { value: "KH", menu: "Cambodia" },
    { value: "CM", menu: "Cameroon" },
    { value: "CA", menu: "Canada" },
    { value: "CV", menu: "Cape Verde" },
    { value: "CF", menu: "Central African Republic" },
    { value: "TD", menu: "Chad" },
    { value: "CL", menu: "Chile" },
    { value: "CN", menu: "China" },
    { value: "CO", menu: "Colombia" },
    { value: "KM", menu: "Comoros" },
    { value: "CD", menu: "Congo (DRC)" },
    { value: "CG", menu: "Congo (Republic)" },
    { value: "CR", menu: "Costa Rica" },
    { value: "CI", menu: "Côte d’Ivoire" },
    { value: "HR", menu: "Croatia" },
    { value: "CU", menu: "Cuba" },
    { value: "CY", menu: "Cyprus" },
    { value: "CZ", menu: "Czech Republic" },
    { value: "DK", menu: "Denmark" },
    { value: "DJ", menu: "Djibouti" },
    { value: "DM", menu: "Dominica" },
    { value: "DO", menu: "Dominican Republic" },
    { value: "EC", menu: "Ecuador" },
    { value: "EG", menu: "Egypt" },
    { value: "SV", menu: "El Salvador" },
    { value: "GQ", menu: "Equatorial Guinea" },
    { value: "ER", menu: "Eritrea" },
    { value: "EE", menu: "Estonia" },
    { value: "SZ", menu: "Eswatini" },
    { value: "ET", menu: "Ethiopia" },
    { value: "FJ", menu: "Fiji" },
    { value: "FI", menu: "Finland" },
    { value: "FR", menu: "France" },
    { value: "GA", menu: "Gabon" },
    { value: "GM", menu: "Gambia" },
    { value: "GE", menu: "Georgia" },
    { value: "DE", menu: "Germany" },
    { value: "GH", menu: "Ghana" },
    { value: "GR", menu: "Greece" },
    { value: "GD", menu: "Grenada" },
    { value: "GT", menu: "Guatemala" },
    { value: "GN", menu: "Guinea" },
    { value: "GW", menu: "Guinea-Bissau" },
    { value: "GY", menu: "Guyana" },
    { value: "HT", menu: "Haiti" },
    { value: "HN", menu: "Honduras" },
    { value: "HU", menu: "Hungary" },
    { value: "IS", menu: "Iceland" },
    { value: "IN", menu: "India" },
    { value: "ID", menu: "Indonesia" },
    { value: "IR", menu: "Iran" },
    { value: "IQ", menu: "Iraq" },
    { value: "IE", menu: "Ireland" },
    { value: "IL", menu: "Israel" },
    { value: "IT", menu: "Italy" },
    { value: "JM", menu: "Jamaica" },
    { value: "JP", menu: "Japan" },
    { value: "JO", menu: "Jordan" },
    { value: "KZ", menu: "Kazakhstan" },
    { value: "KE", menu: "Kenya" },
    { value: "KI", menu: "Kiribati" },
    { value: "KR", menu: "South Korea" },
    { value: "KW", menu: "Kuwait" },
    { value: "KG", menu: "Kyrgyzstan" },
    { value: "LA", menu: "Laos" },
    { value: "LV", menu: "Latvia" },
    { value: "LB", menu: "Lebanon" },
    { value: "LS", menu: "Lesotho" },
    { value: "LR", menu: "Liberia" },
    { value: "LY", menu: "Libya" },
    { value: "LI", menu: "Liechtenstein" },
    { value: "LT", menu: "Lithuania" },
    { value: "LU", menu: "Luxembourg" },
    { value: "MG", menu: "Madagascar" },
    { value: "MW", menu: "Malawi" },
    { value: "MY", menu: "Malaysia" },
    { value: "MV", menu: "Maldives" },
    { value: "ML", menu: "Mali" },
    { value: "MT", menu: "Malta" },
    { value: "MH", menu: "Marshall Islands" },
    { value: "MR", menu: "Mauritania" },
    { value: "MU", menu: "Mauritius" },
    { value: "MX", menu: "Mexico" },
    { value: "FM", menu: "Micronesia" },
    { value: "MD", menu: "Moldova" },
    { value: "MC", menu: "Monaco" },
    { value: "MN", menu: "Mongolia" },
    { value: "ME", menu: "Montenegro" },
    { value: "MA", menu: "Morocco" },
    { value: "MZ", menu: "Mozambique" },
    { value: "MM", menu: "Myanmar (Burma)" },
    { value: "NA", menu: "Namibia" },
    { value: "NR", menu: "Nauru" },
    { value: "NP", menu: "Nepal" },
    { value: "NL", menu: "Netherlands" },
    { value: "NZ", menu: "New Zealand" },
    { value: "NI", menu: "Nicaragua" },
    { value: "NE", menu: "Niger" },
    { value: "NG", menu: "Nigeria" },
    { value: "NO", menu: "Norway" },
    { value: "OM", menu: "Oman" },
    { value: "PK", menu: "Pakistan" },
    { value: "PW", menu: "Palau" },
    { value: "PA", menu: "Panama" },
    { value: "PG", menu: "Papua New Guinea" },
    { value: "PY", menu: "Paraguay" },
    { value: "PE", menu: "Peru" },
    { value: "PH", menu: "Philippines" },
    { value: "PL", menu: "Poland" },
    { value: "PT", menu: "Portugal" },
    { value: "QA", menu: "Qatar" },
    { value: "RO", menu: "Romania" },
    { value: "RU", menu: "Russia" },
    { value: "RW", menu: "Rwanda" },
    { value: "KN", menu: "Saint Kitts and Nevis" },
    { value: "LC", menu: "Saint Lucia" },
    { value: "VC", menu: "Saint Vincent and the Grenadines" },
    { value: "WS", menu: "Samoa" },
    { value: "SM", menu: "San Marino" },
    { value: "ST", menu: "Sao Tome and Principe" },
    { value: "SA", menu: "Saudi Arabia" },
    { value: "SN", menu: "Senegal" },
    { value: "RS", menu: "Serbia" },
    { value: "SC", menu: "Seychelles" },
    { value: "SL", menu: "Sierra Leone" },
    { value: "SG", menu: "Singapore" },
    { value: "SK", menu: "Slovakia" },
    { value: "SI", menu: "Slovenia" },
    { value: "SB", menu: "Solomon Islands" },
    { value: "SO", menu: "Somalia" },
    { value: "ZA", menu: "South Africa" },
    { value: "ES", menu: "Spain" },
    { value: "LK", menu: "Sri Lanka" },
    { value: "SD", menu: "Sudan" },
    { value: "SR", menu: "Suriname" },
    { value: "SE", menu: "Sweden" },
    { value: "CH", menu: "Switzerland" },
    { value: "SY", menu: "Syria" },
    { value: "TW", menu: "Taiwan" },
    { value: "TJ", menu: "Tajikistan" },
    { value: "TZ", menu: "Tanzania" },
    { value: "TH", menu: "Thailand" },
    { value: "TL", menu: "Timor-Leste" },
    { value: "TG", menu: "Togo" },
    { value: "TO", menu: "Tonga" },
    { value: "TT", menu: "Trinidad and Tobago" },
    { value: "TN", menu: "Tunisia" },
    { value: "TR", menu: "Turkey" },
    { value: "TM", menu: "Turkmenistan" },
    { value: "TV", menu: "Tuvalu" },
    { value: "UG", menu: "Uganda" },
    { value: "UA", menu: "Ukraine" },
    { value: "AE", menu: "United Arab Emirates" },
    { value: "GB", menu: "United Kingdom" },
    { value: "US", menu: "United States" },
    { value: "UY", menu: "Uruguay" },
    { value: "UZ", menu: "Uzbekistan" },
    { value: "VU", menu: "Vanuatu" },
    { value: "VA", menu: "Vatican City" },
    { value: "VE", menu: "Venezuela" },
    { value: "VN", menu: "Vietnam" },
    { value: "YE", menu: "Yemen" },
    { value: "ZM", menu: "Zambia" },
    { value: "ZW", menu: "Zimbabwe" }
];
